### ISSUE TITLE
Installation trouble - failed to build the native extension

### ISSUE THREAD

**Issue by yokem55** [jeremyevans/sequel_pg#18]
With Postgres 9.4 and the pg-0.18.1 gem installed sequel_pg fails to compile it's native extension. Whetther allowing the extconfig run pg_config or by manually  setting the env vars, the complile fails diuring the link phase:
<addr>
```
POSTGRES_LIB=/usr/lib64/postgresql-9.4/lib64/ POSTGRES_INCLUDE=/usr/include/postgresql-9.4/ gem install sequel_pg
Building native extensions.  This could take a while...
ERROR:  Error installing sequel_pg:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby19 extconf.rb
checking for main() in -lpq... yes
checking for libpq-fe.h... yes
checking for PQsetSingleRowMode()... yes
creating Makefile

make  clean

make
compiling sequel_pg.c
sequel_pg.c: In function ‘spg__yield_each_row’:
sequel_pg.c:873:11: warning: variable ‘conn’ set but not used [-Wunused-but-set-variable]
   PGconn *conn;
           ^
linking shared-object sequel_pg.so
sequel_pg.o: In function `spg__flush_results':
sequel_pg.c:(.text+0x338): undefined reference to `pg_get_pgconn'
sequel_pg.o: In function `spg_set_single_row_mode':
sequel_pg.c:(.text+0x188f): undefined reference to `pg_get_pgconn'
sequel_pg.o: In function `spg__yield_each_row':
sequel_pg.c:(.text+0x1a04): undefined reference to `pg_get_pgconn'
sequel_pg.c:(.text+0x1a49): undefined reference to `pgresult_get'
sequel_pg.c:(.text+0x1bb7): undefined reference to `pgresult_get'
sequel_pg.o: In function `spg_yield_hash_rows':
sequel_pg.c:(.text+0x1da4): undefined reference to `pgresult_get'
collect2: error: ld returned 1 exit status
Makefile:214: recipe for target 'sequel_pg.so' failed
make: *** [sequel_pg.so] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/lib64/ruby/gems/1.9.1/gems/sequel_pg-1.6.11 for inspection.
Results logged to /usr/local/lib64/ruby/gems/1.9.1/extensions/x86_64-linux/1.9.1/sequel_pg-1.6.11/gem_make.out 
```
</addr>

**Comment by yokem55** [comment]
In case you need it :
gcc version 4.8.3 (Gentoo 4.8.3 p1.1, pie-0.5.9) 
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
GNU ld (Gentoo 2.24 p1.4) 2.24

**Comment by jeremyevans** [comment]
Those function references are supposed to be undefined, as the functions are defined by the pg gem.  Maybe your linker flags are turning that into an error?

For some reason, your linker is complaining because the function reference is not defined at compile time.  This isn't generally a problem on unix-like operating systems, as long as the function reference is defined at runtime.  In sequel_pg's case, that will be true, since sequel_pg will be required after pg.  I know Windows doesn't allow it, which is why sequel_pg no longer works on Windows.

Any chance your linker defaults to `--no-allow-shlib-undefined`?  You might want to add`--allow-shlib-undefined` in the linker flags and see if that changes anything.

Can you install sequel_pg correctly on other operating systems?

**Comment by yokem55** [comment]
The Makefile that extconf.rb writes lists the ldflags line as below:
` ldflags  = -L. -Wl,-O1 -Wl,--as-needed -rdynamic -Wl,-export-dynamic -Wl,--no-undefined`
Manually changing that line in the Makefile to:
`ldflags  = -L. -Wl,-O1 -Wl,--as-needed -rdynamic -Wl,-export-dynamic -Wl,--allow-shlib-undefined`
and then running make again in the installed gem directory, allows the compile to complete.

I'm not sure though how to force this change with mkmf in extconf.rb as it looks like this --no-undefined is default with the binutils that I have....

**Comment by yokem55** [comment]
Hmm it looks like that --no-undefined flag is comfing from the rbconfig.rb file:
```
CONFIG["LDFLAGS"] = "-L. -Wl,-O1 -Wl,--as-needed -rdynamic -Wl,-export-dynamic -Wl,--no-undefined"
```

**Comment by yokem55** [comment]
The Gentoo folks when dealing with this type of problem manually change the makefile in extconf.rb after it is created with create_makefile().

Adding this to extconf.rb after line 19 -- `create_makefile("sequel_pg")`
``` 
  #Check for --no-unefined ldflag -- fix for Gentoo users
  makefile = File.read('./Makefile')
  fixed_makefile = makefile.gsub( /\s-Wl,--no-undefined\s/, "\n")
  File.open('Makefile', "w") {|file| file.puts fixed_makefile }
```
allows the gem to install properly.  Not sure if you want this solution in our code though.

**Comment by jeremyevans** [comment]
I don't think that is a good solution in the general case, though it probably works fine in Gentoo's specific case.  I'll add a note about this to the README.
