### ISSUE TITLE
Segfault with 1.6.11 when errors are swallowed

### ISSUE THREAD

**Issue by jasonrclark** [jeremyevans/sequel_pg#19]
Had a bug that we're fixing in `newrelic_rpm` where out Sequel extension would swallow errors it shouldn't from within `log_yield`.

This was plainly a problem in our code, but on `sequel_pg` 1.6.11 it resulted in a segfault which doesn't seem good either. 1.6.10 has errors from the bad behavior here, but not segfaults.

I've made as minimal a repro case as I could at https://github.com/jasonrclark/sequel_pg-eat_errors_repro in case you're interested. We should have a new agent out today with the patch that addresses the bug on our side.

cc @tkrajcar @ollie

**Comment by jeremyevans** [comment]
Thanks for reporting. I can reproduce the error.  Unfortunately, the backtrace is not helpful, so it may take a while to track down the root cause.

The only change between 1.6.10 and 1.6.11 is support for pg 0.18+, but that requires calling C functions defined in the pg gem.  The problem must be related to that, but it's not something that can be reverted, since it's required when working on pg 0.18+.

**Comment by jasonrclark** [comment]
Yeah, the root cause there didn't seem at all obvious to me from the changes between 1.6.10 and 1.6.11.

FWIW, we just shipped 3.11.1 of `newrelic_rpm` which stops our bad error swallowing, so unless someone else has made the same mistake in an extension, it probably isn't a big deal that it might take a while.

Appreciate all your awesome work on Sequel!

**Comment by jeremyevans** [comment]
Can you test this new code and let me know if it fixes your issue?  It does in my testing.  After I hear from you, I'll release a new version of sequel_pg.

**Comment by jasonrclark** [comment]
Checked it out against my test I sent you and the original duplication case I got from a client, and both look to be working correctly. Thanks for the quick turnaround!

**Comment by jeremyevans** [comment]
Awesome!  I'll push out the sequel_pg 1.6.12 gem shortly.  Thanks again for your help reporting and testing.

**Comment by ollie** [comment]
You guys are awesome, thank you so much for your fixes! :heart:
