### ISSUE TITLE
README RbConfig::Config -> CONFIG

### ISSUE THREAD

**Issue by Luiji** [jeremyevans/sequel_pg#20]
The README file refers to `RbConfig::Config` towards the end (particularly `RbConfig::Config['LDFLAGS']`) when in actuality the name of the constant is `RbConfig::CONFIG`.

~~~
$ ruby -e 'p RbConfig::Config["LDFLAGS"]'
-e:1:in `<main>': uninitialized constant RbConfig::Config (NameError)
$ ruby -e 'p RbConfig::CONFIG["LDFLAGS"]'
"-L. -Wl,-O1 -Wl,--as-needed -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,--no-undefined"
~~~

**Comment by jeremyevans** [comment]
Good catch, thanks for letting me know.  I'll fix this soon.
