### ISSUE TITLE
No stream in Sequel 5

### ISSUE THREAD

**Issue by baelter** [jeremyevans/sequel_pg#24]
`DB.extension :pg_streaming`
`Sequel::Postgres.supports_streaming? => true`
yet
`NoMethodError: undefined method `stream' for #<Sequel::Postgres::Dataset:0x007f7ff41fc388>`

ruby 2.4.1
sequel 5.0.0
sequel_pg 1.7.1
pg 0.21.0
postgresql 9.6.3

**Comment by jeremyevans** [comment]
I can't recreate this in my environment.  Can you try replicating this on another machine to make sure it isn't a local issue?  Can you provide a minimal self-contained example showing the problem?

**Comment by jeremyevans** [comment]
Closing due to lack of response.  If you are able to replicate this on another machine and can provide a minimal, self-contained example showing the problem, please add a comment and this can be reopened.

**Comment by baelter** [comment]
Sorry, ok to close. Never figured out why I was getting this error but starting off fresh resolved it.
