### ISSUE TITLE
Behaviour of sequel_pg with utf8 column names is different from without

### ISSUE THREAD

**Issue by bananarne** [jeremyevans/sequel_pg#26]
SELECT  ("custom_fields" -> 'äää') AS "äää" FROM "table"

yields [{:äää=>"xxx"}] without sequel_pg 
and [:"\xC3\xA4\xC3\xA4\xC3\xA4"=>"xxx"] with

**Comment by bananarne** [comment]
DB.select(Sequel.as(1,ä)).all works to reproduce

**Comment by jeremyevans** [comment]
Thanks for the report.  This is definitely a bug that should be fixed, I'll work on it right away.

**Comment by jeremyevans** [comment]
Fixed by 7a7c827885f45ab3fb9b0a633d9a5a3b52a545d5

**Comment by bananarne** [comment]
Thanks you!
