### ISSUE TITLE
undefined symbol: pgresult_get

### ISSUE THREAD

**Issue by feuerbach** [jeremyevans/sequel_pg#29]
For some reason I'm running into `undefined symbol: pgresult_get` when trying to load `sequel_pg`. Do you have any thoughts as to why that may be?

```
% cat Gemfile
source 'http://rubygems.org'
gem 'sequel_pg'

% bundle install --path vendor/bundle
Fetching gem metadata from http://rubygems.org/..............
Using bundler 1.16.1
Fetching pg 1.1.3
Installing pg 1.1.3 with native extensions
Fetching sequel 5.14.0
Installing sequel 5.14.0
Fetching sequel_pg 1.11.0
Installing sequel_pg 1.11.0 with native extensions
Bundle complete! 1 Gemfile dependency, 4 gems now installed.
Bundled gems are installed into `./vendor/bundle`

% bundle console
Traceback (most recent call last):
        19: from /bin/bundle:23:in `<main>'
        18: from /bin/bundle:23:in `load'
        17: from /usr/share/gems/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
        16: from /usr/share/gems/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
        15: from /usr/share/gems/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
        14: from /usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
        13: from /usr/share/gems/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
        12: from /usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
        11: from /usr/share/gems/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
        10: from /usr/share/gems/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
         9: from /usr/share/gems/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
         8: from /usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli.rb:455:in `console'
         7: from /usr/share/gems/gems/bundler-1.16.1/lib/bundler/cli/console.rb:15:in `run'
         6: from /usr/share/gems/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
         5: from /usr/share/gems/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
         4: from /usr/share/gems/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
         3: from /usr/share/gems/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
         2: from /usr/share/gems/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
         1: from /usr/share/gems/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/share/gems/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require': /home/feuerbach/tst/sequel-pg/vendor/bundle/ruby/2.5.0/extensions/x86_64-linux/2.5.0/sequel_pg-1.11.0/sequel_pg.so: undefined symbol: pgresult_get - /home/feuerbach/tst/sequel-pg/vendor/bundle/ruby/2.5.0/extensions/x86_64-linux/2.5.0/sequel_pg-1.11.0/sequel_pg.so (LoadError)

% ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

% lsb_release -d
Description:    Fedora release 29 (Twenty Nine)
```

**Comment by jeremyevans** [comment]
`pgresult_get` comes from the `pg` gem.  It could be your system doesn't support calling functions in one dlopened library from a different dlopened library.  if that is the case, you need to change your configuration to support that or you will not be able to use sequel_pg.

**Comment by feuerbach** [comment]
I also reproduced this on Ubuntu 18.10. I'm surprised that there aren't more people affected by this.

**Comment by celsworth** [comment]
Can confirm this affects Ubuntu 18.10 clean install.

**Comment by jeremyevans** [comment]
Well, something must have changed in Ubuntu's compilation/dlopen environment to disallow what was previously allowed. I'll happily accept a PR if there is a way to fix the issue with link flags (`LDFLAGS=-Wl,--no-as-needed` maybe), or to document how to get dlopen to work at runtime.

Unfortunately, there really isn't a way to work around the issue.  sequel_pg uses the following functions defined by pg:

```c
PGconn* pg_get_pgconn(VALUE);
PGresult* pgresult_get(VALUE);
```

These functions return pointers, not ruby objects, and therefore you can't have a ruby method that will return the values that sequel_pg could call.

The only alternative would be to duplicate the pg code (structure definitions and functions), which would break badly any time there was a change in pg.  I could use a much stricter version guard I guess, but that's not something I want to do just to appease certain operating systems.

**Comment by feuerbach** [comment]
@celsworth that's interesting, I'm getting the same error on Ubuntu 18.04.

**Comment by celsworth** [comment]
Sorry, you are right. Not sure how I managed to arrive at that wrong conclusion. I don't have any older versions of Ubuntu to hand to test easily at the moment. But its curious if this has been broken for at least 6 months and nobody's noticed.

**Comment by feuerbach** [comment]
Ok, the fix is simple: `require 'pg'` before you `require 'sequel_pg'`.

**Comment by jeremyevans** [comment]
So nothing is broken, and everything is working as designed. :) Note that you should never be requiring `sequel_pg`.  As the README explains, Sequel will pick up `sequel_pg` automatically, and will only load it if `pg` has been loaded first.

**Comment by feuerbach** [comment]
Yes—that makes sense. I think I was debugging a different issue and (wrongly) used `require 'sequel_pg`' in a minimal example.
