### ISSUE TITLE
Support for jruby?

### ISSUE THREAD

**Issue by krainboltgreene** [jeremyevans/sequel_pg#32]
Hello, I'm using jruby and when I try to install sequel_pg it wants to install pg, but for jruby people use jruby-pg. Any chance of supporting that?

**Comment by jeremyevans** [comment]
Not really.  You would basically need to rewrite the C extension in Java.  Someone who knows Java is welcome and encouraged to publish a `jruby-sequel_pg` library.

In general, sequel_pg is an optional library, so if you can't install it, it shouldn't be a big deal.
