### ISSUE TITLE
1.12.1 Fails to Install on macOS with Postgres.app 

### ISSUE THREAD

**Issue by ylg** [jeremyevans/sequel_pg#33]
I've tried most of the many workarounds often proposed to get the pg gem to install when it is being troublesome on macOS (though that gem is having no troubles in this case), but none work for sequel_pg 1.12.1. Since sequel_pg 1.12.0 works, I'm guessing the breaking change is https://github.com/jeremyevans/sequel_pg/issues/31

```
checking for -lpq... yes
checking for libpq-fe.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=[...]/ruby-2.6.3/bin/$(RUBY_BASE_NAME)
	--with-libpq-config
	--without-libpq-config
	--with-pkg-config
	--without-pkg-config
	--with-pqlib
	--without-pqlib
Could not find PostgreSQL build environment (libraries & headers): Makefile not created
```

And mkmf.log just echoes that notion, i.e., libpq-fe.h is not found.

_Note, I'm testing this on a brand new Mac with factory-installed 10.14.5 and Xcode 10.2.1 as the first and only Xcode install, ditto Postgres.app 2.3b1. CLI tools are installed, no other native gems, including pg, are having issues, nor is the previous version of sequel_pg. PATH includes the correct binaries for Postgres._

**Comment by jeremyevans** [comment]
Thanks for the report. I'll prepare a 1.12.2 release today or tomorrow that reverts #31.

**Comment by jeremyevans** [comment]
Revert committed (https://github.com/jeremyevans/sequel_pg/commit/5597791c071643f608852a2174d9ff93827f0d85) and 1.12.2 gem released

**Comment by thomvil** [comment]
i'm having the same problem again with version 1.14.0

**Comment by jeremyevans** [comment]
@thomvil  You shouldn't be having the same problem, as the pkg_config changes causing this issue were reverted.  You may be having a different problem, in which case you should file an issue, and provide full details.   Before filing an issue, you should check that you are not able to fix it by specifying the POSTGRES_INCLUDE and POSTGRES_LIB environment variables for the paths to the PostgreSQL include and shared library files.
