### ISSUE TITLE
IPAddr native implementation breaks Model#save

### ISSUE THREAD

**Issue by slowbro** [jeremyevans/sequel_pg#35]
Hey there - I noticed that as of 1.10.0 inet is cast to an IPAddr - which is great! However, it seems to be interfering with Sequel::Model. I have have a simple test table like so:

- id serial primary key
- address inet
- label varchar

When I save a new row, I set address with a String object. It gets translated to IPAddr (cool), but breaks subsequent `#save` calls.

> can't express #<IPAddr: IPv4:192.168.0.1/255.255.255.255> as a SQL literal

I'm using ruby 2.6.5 (via rvm), and have verified this happening on multiple systems (Arch, FreeBSD 11, FreeBSD 12). I tested with a fresh gemset, and only installed `sequel`, and `sequel_pg`.

```
[katelyn@h ~]$ ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
[katelyn@h ~]$ gem list | egrep '(pg|sequel)'
pg (1.2.3)
sequel (5.30.0)
sequel_pg (1.12.5)
```

Here's a short barebones test script:

```
require 'sequel'

DB = Sequel.connect( 'postgres://postgres:test@172.17.0.2:5432/postgres?search_path=test' )

DB.create_table( :tests ) do
    primary_key :id
    inet :address
    varchar :label
end

class Test < Sequel::Model
end

t = Test.new( address: '192.168.0.1' )
t.save

puts "Created: #{t.inspect}"

tt = Test.find( address: '192.168.0.1' )

puts "Found: #{tt.inspect}"

begin
    tt.label = 'something'
    tt.save
rescue => e
    puts "Exception: #{e.message}"
end

tt = Test.find( address: '192.168.0.1' )
puts "Final: #{tt.inspect}"

DB.drop_table( :tests )
````

With just sequel and pg, I get this:

```
[katelyn@h ~]$ ruby test.rb 
Created: #<Test @values={:id=>1, :address=>"192.168.0.1", :label=>nil}>
Found: #<Test @values={:id=>1, :address=>"192.168.0.1", :label=>nil}>
Final: #<Test @values={:id=>1, :address=>"192.168.0.1", :label=>"something"}>
```

But, with sequel_pg installed, I get this:

```
[katelyn@h ~]$ ruby test.rb 
Created: #<Test @values={:id=>1, :address=>#<IPAddr: IPv4:192.168.0.1/255.255.255.255>, :label=>nil}>
Found: #<Test @values={:id=>1, :address=>#<IPAddr: IPv4:192.168.0.1/255.255.255.255>, :label=>nil}>
Exception: can't express #<IPAddr: IPv4:192.168.0.1/255.255.255.255> as a SQL literal
Final: #<Test @values={:id=>1, :address=>#<IPAddr: IPv4:192.168.0.1/255.255.255.255>, :label=>nil}>
```

Sorry if this is expected behavior (i.e. I should re-cast `address`) or something; not really keen on Postgres and Sequel, but learning!

**Comment by slowbro** [comment]
It was brought to my attention after putting this in that I should probably be using `#save_changes` or `#update`; which both work.

However, I still would expect this to work in both directions, since `@address` gets set as an IPAddr object (i.e. the 'native' form of an `inet` col). Just like a `varchar` is a `String` and can be modified in place as such. And the sequel docs state:

> save (opts=OPTS)
>     Creates or updates the record

**Comment by jeremyevans** [comment]
You currently need to load the pg_inet extension into the `Sequel::Database` object, then things will work correctly.  I haven't yet decided whether to integrate the rest of pg_inet into the Sequel postgres adapter directly.

The behavior you are seeing is currently expected, though it is suboptimal in that sense.  However, not parsing inet types to IPAddr objects in sequel_pg by default would slow things down (rather, checking for whether to do so would slow things down), which isn't good either.  So I made a tradeoff that sequel_pg parses inet to IPAddr by default for maximum performance, but the literalizer (in the pg_inet extension) still must be loaded manually if you want to use the IPAddr objects in queries (such as saving them or using them in filter conditions).

**Comment by slowbro** [comment]
Thanks, that makes a lot of sense. I appreciate your time!
