### ISSUE TITLE
disable native IPAddr for cidr ranges

### ISSUE THREAD

**Issue by beanieboi** [jeremyevans/sequel_pg#36]
Hey Jeremy,

i really appreciate the effort you are putting into Sequel and sequel-pg.
We are currently upgrading sequel-pg and running into a couple of problems with parsing of cidr fields into IPAddr objects.

IPAddr is not made for CIDR blocks. It can store the prefix but if you try to use it with a CIDR Block it quickly falls apart.

1. Issue
Calling `.to_s` swallows the prefix. example: `IPAddr.new("98.51.100.0/23").to_s` returns `"98.51.100.0"` which is not the same.

2. Issue
Comparing IPAddr works unexpected with CIDR blocks.
```
$ ip1 = IPAddr.new("98.51.100.0/24")
$ ip2= IPAddr.new("98.51.100.0/23")
ip1==ip2
=> true
```
those are not the same CIDR blocks.

Is there a way to disable the native IPAddr conversion? We find ourselves in a place where we have to undo the conversions in our Sequel Models with getters by converting them back to strings to avoid any kind of issues. We tried to work with IPAddr internally but it has too many edge cases which are unexpected with `IPAddr`

We are using the NetAddr gem (https://github.com/dspinhirne/netaddr-rb). Is there a way to tell sequel-pg to return a NetAddr object instead of a IPAddr object? We really like the idea of supporting many native types. Our application is very deep in the networking domain and has to deal with a lot of Ipaddress, subnets etc.

thank you for all your efforts any input is greatly appreciated

**Comment by jeremyevans** [comment]
I suppose in this case, we could have sequel_pg check whether there is a conversion proc for the type, and use the conversion proc if so.  That would allow you to use a custom conversion proc that uses netaddr.  Using conversion procs in favor of hard-coded conversions is not done in general for performance reasons, but considering that IPAddr creation is more expensive than the other hard-coded conversions, it is something I'm willing to consider for this particular case.

Doing that will probably require coordination with Sequel, so that the pg_inet extension does not add a conversion proc if sequel_pg is in use (otherwise, loading the pg_inet extension would decrease performance).

This change should not be difficult to implement in sequel_pg.  Would you feel comfortable submitting a PR for it?  The change would need to be made around line 934 of sequel_pg.c.

**Comment by beanieboi** [comment]
awesome, I'll work on a PR

**Comment by beanieboi** [comment]
alright, I'm genuinely confused. it's already possible to overwrite the conversion proc's?

In order to start the PR I created a small example and while reading the C code I found that `pg_inet` is already working that way.

Gemfile:
```
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sequel_pg"#, require: "sequel", path: "../"
gem "pry"
gem "netaddr"
```

example.rb
```
require "bundler"

Bundler.setup

require "sequel"
require "pry"
require "netaddr"

DB = Sequel.connect('postgres://ben:@localhost/sequel_pg_test') # requires pg
DB.extension :pg_inet

DB.instance_exec do
  inet_oid = 869
  cidr_oid = 650
  ip = NetAddr::IPv4.method(:parse)
  ip_net = NetAddr::IPv4Net.method(:parse)
  string = String.method(:new)
  add_conversion_proc(inet_oid, ip)
  add_conversion_proc(cidr_oid, ip_net)
end

# DB.create_table :networks do
#   primary_key :id
#   inet :ip_addr
#   cidr :cidr_block
# end

networks = DB[:networks]
# networks.insert(ip_addr: '192.168.0.1', cidr_block: "192.168.0.0/28")

p networks.all
```

are there any drawbacks to that approach? I know it's not really public API so it's risky for us to depend on it?

P.S.: if you did that intentionally, that's genius :)

**Comment by jeremyevans** [comment]
It is intentional in Sequel that users have control over the conversion procs.  `add_conversion_proc` is public API for that reason.

However, sequel_pg doesn't use the conversion procs for types it has native support for, as doing so decreases performance.  That's why you would need to change sequel_pg.  

```
DB.add_conversion_proc(650, proc{|s| s})
DB.get(Sequel.cast('127.0.0.1', :cidr))
# with sequel_pg: #<IPAddr: IPv4:127.0.0.1/255.255.255.255>
# without sequel_pg: "127.0.0.1/32"
```

I'm not sure how your example could work if the current version of sequel_pg is loaded, but maybe I'm missing something.

**Comment by beanieboi** [comment]
ok, I found my mistake. Bundler does not compile C extensions if you use a `path` option. I need to compile it manually with `rake-compiler`. Now I got a working development workflow.

You pointed to to line 934, but that is not getting called. instead all my changes are near line 1085.
I came up with the following changes. (disclaimer, I haven't done C since university :))

Any feedback is appreciated, before I open a PR.

```diff
diff --git a/ext/sequel_pg/sequel_pg.c b/ext/sequel_pg/sequel_pg.c
index 6ba397a..0fa6d89 100644
--- a/ext/sequel_pg/sequel_pg.c
+++ b/ext/sequel_pg/sequel_pg.c
@@ -1018,6 +1018,8 @@ static VALUE spg__col_value(VALUE self, PGresult *res, long i, long j, VALUE* co
   VALUE array_type;
   VALUE scalar_oid;
   struct spg_blob_initialization bi;
+  VALUE conv_procs = 0;
+  VALUE conversion_proc = 0;
 
   if(PQgetisnull(res, i, j)) {
     rv = Qnil;
@@ -1081,7 +1083,18 @@ static VALUE spg__col_value(VALUE self, PGresult *res, long i, long j, VALUE* co
         break;
       case 869: /* inet */
       case 650: /* cidr */
-        rv = spg_inet(v, PQgetlength(res, i, j));
+        if (conv_procs == 0) {
+          conv_procs = rb_funcall(rb_funcall(self, spg_id_db, 0), spg_id_conversion_procs, 0);
+        }
+        conversion_proc = rb_funcall(conv_procs, spg_id_get, 1, INT2NUM(ftype));
+
+        if (conversion_proc != Qnil) {
+          rv = rb_tainted_str_new(v, PQgetlength(res, i, j));
+          rv = rb_funcall(conversion_proc, spg_id_call, 1, rv);
+        } else {
+          rv = spg_inet(v, PQgetlength(res, i, j));
+        }
+
         break;
       /* array types */
       case 1009:
```

**Comment by jeremyevans** [comment]
You are correct that you need changes around 1085. You also need changes around 934 to handle `cidr[]` (array of cidr) types.

You don't need all that code around 1085.  If there is a conversion proc,`colconvert[j]` will not be `Qnil`, see line 1236.  I think a simple way to do it would be to add a label to the default block and use goto, or move the 869/650 cases above the default and use fallthrough.  I think my preference would be the latter.

**Comment by beanieboi** [comment]
```diff
diff --git a/ext/sequel_pg/sequel_pg.c b/ext/sequel_pg/sequel_pg.c
index 6ba397a..4364a82 100644
--- a/ext/sequel_pg/sequel_pg.c
+++ b/ext/sequel_pg/sequel_pg.c
@@ -872,6 +872,8 @@ static VALUE spg_fetch_rows_set_cols(VALUE self, VALUE ignore) {
 
 static VALUE spg__array_col_value(char *v, size_t length, VALUE converter, int enc_index, int oid, VALUE db) {
   VALUE rv;
+  VALUE conv_procs = 0;
+  VALUE conversion_proc = 0;
   struct spg_blob_initialization bi;
 
   switch(oid) {
@@ -931,7 +933,16 @@ static VALUE spg__array_col_value(char *v, size_t length, VALUE converter, int e
       break;
     case 869: /* inet */
     case 650: /* cidr */
-      rv = spg_inet(v, length);
+      if (conv_procs == 0) {
+        conv_procs = rb_funcall(rb_funcall(db, spg_id_db, 0), spg_id_conversion_procs, 0);
+      }
+      conversion_proc = rb_funcall(conv_procs, spg_id_get, 1, INT2NUM(oid));
+      if (conversion_proc != Qnil) {
+        rv = rb_tainted_str_new(v, length);
+        rv = rb_funcall(conversion_proc, spg_id_call, 1, rv);
+      } else {
+        rv = spg_inet(v, length);
+      }
       break;
     default:
       rv = rb_tainted_str_new(v, length);
@@ -1079,10 +1090,6 @@ static VALUE spg__col_value(VALUE self, PGresult *res, long i, long j, VALUE* co
         rv = rb_tainted_str_new(v, PQgetlength(res, i, j));
         PG_ENCODING_SET_NOCHECK(rv, enc_index);
         break;
-      case 869: /* inet */
-      case 650: /* cidr */
-        rv = spg_inet(v, PQgetlength(res, i, j));
-        break;
       /* array types */
       case 1009:
       case 1014:
@@ -1230,6 +1237,12 @@ static VALUE spg__col_value(VALUE self, PGresult *res, long i, long j, VALUE* co
         }
         rv = spg_array_value(v, PQgetlength(res, i, j), colconvert[j], enc_index, scalar_oid, self, array_type);
         break;
+      case 869: /* inet */
+      case 650: /* cidr */
+        if (colconvert[j] == Qnil) {
+          rv = spg_inet(v, PQgetlength(res, i, j));
+          break;
+        }
       default:
         rv = rb_tainted_str_new(v, PQgetlength(res, i, j));
         PG_ENCODING_SET_NOCHECK(rv, enc_index);
```

I had to find the proc's for the array type on the fly. `converter` is set during initialization and I didn't find a way to to overwrite it. `converter` would always be `IPAddr.method(:new)`.

**Comment by beanieboi** [comment]
I opened https://github.com/jeremyevans/sequel_pg/pull/37 since this discussion is drifting into Code review :)

**Comment by jeremyevans** [comment]
Sounds good.  I'm going to close this now.
