### ISSUE TITLE
Issue with timestamps

### ISSUE THREAD

**Issue by lcx** [jeremyevans/sequel_pg#40]
I just came across an issue with timestamps. 
I have a table exported from a rails project where I needed to analyse some data with sequel, the Timestamps of the table look like this: 

```
 routing_start_date     | timestamp without time zone    |           |          |
 routing_end_date       | timestamp without time zone    |           |          |
 created_at             | timestamp(6) without time zone |           | not null |
 updated_at             | timestamp(6) without time zone |           | not null |
```

As it seems the `timestamp without time zone` cause an issue with `sequel_pg` 

my ruby code looks like this: 

```ruby
    DB = Sequel.connect(ENV.fetch("DATABASE_URL"))
    class HeadNumber < Sequel::Model(:head_numbers)
    end
```

Something like `HeadNumber.count` works, but as soon as I want to see some data `HeadNumber.first` I get an error

```
ArgumentError (unexpected timetamp format, too short)
```
https://github.com/jeremyevans/sequel_pg/blob/master/ext/sequel_pg/sequel_pg.c#L535

Thanks for the typo, I probably wouldn't have found it without it. 
So it seems like it doesn't like my timestamps, not sure if the `timestamp(6) without time zone` or `timestamp without time zone` create the issue, I dropped both and after that it started working. 
I will reimport the DB dump when I'm done to verify which timestamp causes the issue. 

Or even better, I will create some test data in a mini project with sql for import to reproduce this issue.

**Comment by jeremyevans** [comment]
If you can figure out which timestamp value is causing the problem, that would be great.  Once I know what value PostgreSQL is returning, I can modify sequel_pg to handle it.

In spite of the helpfulness of the typo, we should probably also fix that. :)

**Comment by lcx** [comment]
I was worried I can't reproduce it but the issue is something completely different 🤦‍♂️
Good old 'Infinity' 

So having a record like this is fine: 

```sql
insert into public.head_numbers (country_code, area_code, area_code_name, number, routing_start_date, routing_end_date)
VALUES (43, 1, 'Wien', '12345', '2021-03-01 12:12:22', '2021-03-01 12:12:22');
```

But using Infinity (which we use a lot in this project) 

```sql
insert into public.head_numbers (country_code, area_code, area_code_name, number, routing_start_date, routing_end_date)
VALUES (43, 1, 'Wien', '12345', '2021-03-01 12:12:22', 'Infinity');
```

will result in the described error, so this only occurs if any record uses infinity as date.

```
irb(main):019:0> HeadNumber.first
Traceback (most recent call last):
       16: from /bundle/ruby/2.6.0/gems/sequel-5.42.0/lib/sequel/dataset/actions.rb:697:in `single_record'
       15: from /bundle/ruby/2.6.0/gems/sequel-5.42.0/lib/sequel/dataset/actions.rb:709:in `single_record!'
       14: from /bundle/ruby/2.6.0/gems/sequel-5.42.0/lib/sequel/dataset/actions.rb:954:in `with_sql_first'
       13: from /bundle/ruby/2.6.0/gems/sequel-5.42.0/lib/sequel/dataset/actions.rb:944:in `with_sql_each'
       12: from /bundle/ruby/2.6.0/gems/sequel-5.42.0/lib/sequel/adapters/postgres.rb:614:in `fetch_rows'
       11: from /bundle/ruby/2.6.0/gems/sequel-5.42.0/lib/sequel/dataset/actions.rb:1093:in `execute'
       10: from /bundle/ruby/2.6.0/gems/sequel-5.42.0/lib/sequel/adapters/postgres.rb:318:in `execute'
        9: from /bundle/ruby/2.6.0/gems/sequel-5.42.0/lib/sequel/database/connecting.rb:269:in `synchronize'
        8: from /bundle/ruby/2.6.0/gems/sequel-5.42.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
        7: from /bundle/ruby/2.6.0/gems/sequel-5.42.0/lib/sequel/adapters/postgres.rb:318:in `block in execute'
        6: from /bundle/ruby/2.6.0/gems/sequel-5.42.0/lib/sequel/adapters/postgres.rb:522:in `check_database_errors'
        5: from /bundle/ruby/2.6.0/gems/sequel-5.42.0/lib/sequel/adapters/postgres.rb:318:in `block (2 levels) in execute'
        4: from /bundle/ruby/2.6.0/gems/sequel-5.42.0/lib/sequel/adapters/postgres.rb:500:in `_execute'
        3: from /bundle/ruby/2.6.0/gems/sequel-5.42.0/lib/sequel/adapters/postgres.rb:146:in `execute'
        2: from /bundle/ruby/2.6.0/gems/sequel-5.42.0/lib/sequel/adapters/postgres.rb:614:in `block in fetch_rows'
        1: from /bundle/ruby/2.6.0/gems/sequel-5.42.0/lib/sequel/adapters/postgres.rb:614:in `yield_hash_rows'
ArgumentError (unexpected timetamp format, too short)
```

oh man, how much more will this 'Infinity' thing bite me?

**Comment by jeremyevans** [comment]
This is expected behavior.  You need to use the pg_extended_date_support extension and set `DB.convert_infinite_timestamps = 'string' # or 'nil' or 'float'`.

I'll leave this open until I fix the typo.
