### ISSUE TITLE
Possible memory leak when upgrading pg_sequel to 1.15.0

### ISSUE THREAD

**Issue by firstsano** [jeremyevans/sequel_pg#48]
We have sidekiq job which fetches data from postgres and generates some xml reports via streaming. Under normal circumstances it consumes about 300 MB RAM, but after upgrading `pg_sequel` gem from `1.14.0` to `1.15.0` it started to consume about 7GB.

We've double checked this job in isolation downgrading gem to `1.14.0` and the memory usage was fine. We don't use `#paged_each` so the change in default settings shouldn't be the issue.

```
ruby - 3.0.2
pg - 1.4.1
```

Could there be any memory leaks in `1.15.0`?

**Comment by jeremyevans** [comment]
Sequel uses `pg` for streaming if running on a supported version of `pg`.  However, comparing `sequel_pg`'s code to `pg`'s, `spg__yield_each_row_stream` in `sequel_pg` is not clearing the result, unlike `yield_hash` in `pg`.

Can you please try the following patch and let me know if it fixes the issue?:

```diff
diff --git a/ext/sequel_pg/sequel_pg.c b/ext/sequel_pg/sequel_pg.c
index 396008d..a0214c6 100644
--- a/ext/sequel_pg/sequel_pg.c
+++ b/ext/sequel_pg/sequel_pg.c
@@ -1693,6 +1693,7 @@ static void spg__yield_each_row_stream(VALUE rres, int ntuples, int nfields, voi
   } else {
     rb_yield(h);
   }
+  PQclear(res);
 }

 static VALUE spg__yield_each_row_internal(VALUE self, VALUE rconn, VALUE rres, PGresult *res, int enc_index, VALUE *colsyms, VALUE *colconvert) {
```

**Comment by firstsano** [comment]
I have tested the patch and it works like a charm! 🎉 🚀

**Comment by jeremyevans** [comment]
Thank you for testing. I will commit it and put out a new release in a couple days.

**Comment by jeremyevans** [comment]
Sorry, I'm a little sick today, so the release will probably be tomorrow.

**Comment by firstsano** [comment]
No worries, get well 👍
