### ISSUE TITLE
Failed to build gem native extension (Mac OS Ventura)

### ISSUE THREAD

**Issue by delphaber** [jeremyevans/sequel_pg#52]
👋 

I'm trying to install sequel (5.62.0) and sequel_pg (1.17.0) on Ruby 3.1.2 with bundler (2.3.11) on Mac OS Ventura (13) and with PostgreSQL 11 and I've got this error:

```
current directory:
/Users/faber/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel_pg-1.17.0/ext/sequel_pg
/Users/faber/.rbenv/versions/3.1.2/bin/ruby -I /Users/faber/.rbenv/versions/3.1.2/lib/ruby/3.1.0 -r
./siteconf20221108-49950-ho3wst.rb extconf.rb
checking for -lpq... yes
checking for libpq-fe.h... yes
checking for PQsetSingleRowMode()... yes
checking for timegm()... yes
creating Makefile

current directory: /Users/faber/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel_pg-1.17.0/ext/sequel_pg
make DESTDIR\= clean

current directory: /Users/faber/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel_pg-1.17.0/ext/sequel_pg
make DESTDIR\=
compiling sequel_pg.c
sequel_pg.c:27:9: warning: 'ntohll' macro redefined [-Wmacro-redefined]
#define ntohll(c) ((uint64_t)( \
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_endian.h:140:9: note: previous definition
is here
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
        ^
1 warning generated.
linking shared-object sequel_pg.bundle
Undefined symbols for architecture x86_64:
  "_pg_get_pgconn", referenced from:
      _spg_set_single_row_mode in sequel_pg.o
      _spg__flush_results in sequel_pg.o
  "_pg_get_result_enc_idx", referenced from:
      _spg_yield_hash_rows in sequel_pg.o
      _spg__yield_each_row in sequel_pg.o
  "_pgresult_get", referenced from:
      _spg_yield_hash_rows in sequel_pg.o
      _spg__yield_each_row in sequel_pg.o
      _spg__yield_each_row_internal in sequel_pg.o
      _spg__yield_each_row_stream in sequel_pg.o
  "_pgresult_stream_any", referenced from:
      _spg__yield_each_row_internal in sequel_pg.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sequel_pg.bundle] Error 1

make failed, exit code 2
``` 

I've already reinstalled `xcode-select --install` and did a `rbenv uninstall 3.1.2`  `rbenv install 3.1.2` to start over with a clean ruby installation, but this did not work.

```
 ↳ $ xcode-select --version
xcode-select version 2396.
```

Any advice? 🙏 

Note: It was working on Mac OS Monterey (12). It happened after I've upgraded 😬

**Comment by jeremyevans** [comment]
It's expected that the symbols are undefined in sequel_pg, since those symbols are defined in the pg gem.  If a Mac OS upgrade broke the behavior, you could either downgrade Mac OS, or set the appropriate linker flags that allow sequel_pg to build (maybe Mac OS 12 is using `-Wl,--no-undefined` by default, and you need to override that?). 

This isn't consider a bug in sequel_pg, so I'm going to close this issue.  If you have further questions regarding this, please open a discussion.

**Comment by jpaulgs** [comment]
@delphaber did you find a workable solution here?

**Comment by delphaber** [comment]
Hi! The fix that worked (in my case at least) is already in `master`, but a
new gem version has not been released on rubygems yet. Try to install this
gem via GitHub directly

Il Mer 7 Dic 2022, 07:00 Jerome Paul ***@***.***> ha scritto:
